### ISSUE TITLE
gpu-platform

### ISSUE THREAD

**Issue by aaronsace** [djm34/sgminer-msvc2015#15]
When you don't specify a platform, it try's to produce a bin file for the NVidia card in my system then crashes. It should only detect opencl devices, not cuda. 

I noted nicehash's version doesn't try to build a bin for the NVidia card and just detects the amd cards without specifying the platform. Can you see if you have done something different? 

`--gpu-platform <arg> Select OpenCL platform ID to use for GPU mining (default: -1)`

**Comment by djm34** [comment]
sgminer doesn't care about the brand of the card, it just try to build binaries for opencl platform: amd is one, nvidia is another and to some extend intel too...
You need to precise to which platform you run. Luckily, amd cards are on one platform, the intel on another and the nvidia another. 
It is up to you to precise on which platform you want to run. May-be nicehash did differently but I know people interested in being able to run on both amd and nvidia cards with sgminer. So, as far as I am concerned, it isn't in my intention to block nvidia cards on sgminer. Also sgminer allows you to choose platforms and devices on which you want to run.

**Comment by aaronsace** [comment]
Ah, I see. I think I get what's happening now. Nicehash's version does actually appear to work on NVidia as well but this version crashes. I used to only have AMD cards so it's never been an issue but I got an NVidia card for testing MultiPoolMiner. 

Not really bothered about running it on NVidia cards but I will need to workout someway for MultiPoolMiner to select the correct platform for AMD cards. 

Thanks for your help anyway. If you do have any advice on how to get the correct platform id, I would appreciate it.

**Comment by djm34** [comment]
I think there is a command in sgminer to get the platform number (but I haven't used it in a long time and don't remember, but it should be display with --help).
Otherwise trial and error :). In my case, my nvidia cards are always on platform 0 and the amd on platform 1 (but my system uses mainly nvidia...) so may-be it could depends on the order of installation. Usually when I want to run on nvidia I use --platform 0 and amd --platform 1. But I don't think it is possible to run both amd and nvidia cards at the same time, so that's may-be the reason for the crash... In that case you should probably run 2 instances of sgminer
