### ISSUE TITLE
what?

### ISSUE THREAD

**Issue by ZeeFF** [djm34/sgminer-msvc2015#19]
Error -5: Enqueueing kernel onto command queue. (clEnqueueNDRangeKernel)
 GPU 0 failure, disabling!
Cant you make an easy to use miner? 
How in the world you make an excavator that disables all 8 cards at start?

**Comment by djm34** [comment]
by using the correct setting

**Comment by ericpolicastro** [comment]
or just use tdxminer and get 7 times the hash power than this program gets
you. DJM gave up on this project the moment it was released.

**Comment by djm34** [comment]
nice trolling, go back to bitcointalk, where it belongs (the trolling).
Currently main effort on zcoin is developping mtp

**Comment by ericpolicastro** [comment]
That's cool, except for all the blocks being extracted now and over the
last year plus since you gave up and tdxminer made your stuff obsolete

On May 11, 2018 1:02 AM, "djm34" <notifications@github.com> wrote:

nice trolling, go back to bitcointalk, where it belongs (the trolling).
Currently main effort on zcoin is developping mtp

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/djm34/sgminer-msvc2015/issues/19#issuecomment-388268685>,
or mute the thread

**Comment by djm34** [comment]
that the way it is you like it or not. 
At least now, with tdxminer, you are forced to donate to the dev (don't think I ever saw lots of these...  and definitely not enough for suffering such butt hurt comments lol)

**Comment by ericpolicastro** [comment]
2%, yet the miner outperforms msvc2015 by 700-800%. I can live with the
delta.
